apiVersion: v1
kind: Service
metadata:
  name: my-dotnet-app-service
  namespace: default
spec:
  selector:
    app: my-dotnet-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32356  # 🔹 Explicitly set the port
  type: NodePort  # Works for local Kubernetes (Kind)
